[build]
  command = "npm run build"
  publish = "dist/hoodlink/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NETLIFY_USE_YARN_CACHE = "true"
  NETLIFY_CACHE_BUILD = "true"